### ISSUE TITLE
Bug: handling of "false" options for options is broken

### ISSUE THREAD

**Issue by everyonesdesign** [mateuszjanusz/markdown-into-html#1]
If you try to pass the "false" value to a boolean option, it'll use default "true" anyway.

That's because the check for the options presence doesn't allow the "false" value to get through:

```
linkify: (options && options.linkify) || true,
```

In that case default "true" value will be used instead.

I'll create a pull request fixing the issue.

**Comment by mateuszjanusz** [comment]
Released the fix in 1.0.3.

Thanks for your contribution :)
